geojson = "../assets/INPUT/occurence_absence.json"
occurence_absence_dataframe_path =  "../assets/INPUT/occurence_abscence.parquet"
output_file_path = "../generated_files/features.parquet"
explanatory_rasters = [
    '../assets/FEATURES/TEMPERATURE/wc2.1_30s_bio_1.tif',
    '../assets/FEATURES/TEMPERATURE/wc2.1_30s_bio_2.tif',
    '../assets/FEATURES/TEMPERATURE/wc2.1_30s_bio_3.tif',
    '../assets/FEATURES/TEMPERATURE/wc2.1_30s_bio_4.tif',
    '../assets/FEATURES/TEMPERATURE/wc2.1_30s_bio_5.tif',
    '../assets/FEATURES/TEMPERATURE/wc2.1_30s_bio_6.tif',
    '../assets/FEATURES/TEMPERATURE/wc2.1_30s_bio_7.tif',
    '../assets/FEATURES/TEMPERATURE/wc2.1_30s_bio_8.tif',
    '../assets/FEATURES/TEMPERATURE/wc2.1_30s_bio_9.tif',
    '../assets/FEATURES/TEMPERATURE/wc2.1_30s_bio_10.tif',
    '../assets/FEATURES/TEMPERATURE/wc2.1_30s_bio_11.tif',
    '../assets/FEATURES/TEMPERATURE/wc2.1_30s_bio_12.tif',
    '../assets/FEATURES/TEMPERATURE/wc2.1_30s_bio_13.tif',
    '../assets/FEATURES/TEMPERATURE/wc2.1_30s_bio_14.tif',
    '../assets/FEATURES/TEMPERATURE/wc2.1_30s_bio_15.tif',
    '../assets/FEATURES/TEMPERATURE/wc2.1_30s_bio_16.tif',
    '../assets/FEATURES/TEMPERATURE/wc2.1_30s_bio_17.tif',
    '../assets/FEATURES/TEMPERATURE/wc2.1_30s_bio_18.tif',
    '../assets/FEATURES/TEMPERATURE/wc2.1_30s_bio_19.tif',
    '../assets/FEATURES/VEGETACAO/Cultivated_and_Managed_Vegetation.tif',
    '../assets/FEATURES/VEGETACAO/Deciduous_Broadleaf_Trees.tif',
    '../assets/FEATURES/VEGETACAO/Evergreen_Broadleaf_Trees.tif',
    '../assets/FEATURES/VEGETACAO/Herbaceous_Vegetation.tif',
    '../assets/FEATURES/VEGETACAO/Mixed_Other_Trees.tif',
    '../assets/FEATURES/VEGETACAO/Open_Water.tif',
    '../assets/FEATURES/VEGETACAO/Regularly_Flooded_Vegetation.tif',
    '../assets/FEATURES/VEGETACAO/Shrubs.tif',
    '../assets/processed/processed/vegetacao_ibge1992_br.tif',
    '../assets/processed/processed/solos2001_br.tif',
    '../assets/processed/processed/sa2001tree_br.tif',
    '../assets/processed/processed/exposicao_br.tif',
    '../assets/processed/processed/density3_br.tif',
    '../assets/processed/processed/declividade_br.tif',
    '../assets/processed/processed/altitude_br.tif'
]
columns = [
    'BIOVAR1',
    'BIOVAR2',
    'BIOVAR3',
    'BIOVAR4',
    'BIOVAR5',
    'BIOVAR6',
    'BIOVAR7',
    'BIOVAR8',
    'BIOVAR9',
    'BIOVAR10',
    'BIOVAR11',
    'BIOVAR12',
    'BIOVAR13',
    'BIOVAR14',
    'BIOVAR15',
    'BIOVAR16',
    'BIOVAR17',
    'BIOVAR18',
    'BIOVAR19',
    'Cultivated_and_Managed_Vegetation',
    'Deciduous_Broadleaf_Trees',
    'Evergreen_Broadleaf_Trees',
    'Herbaceous_Vegetation',
    'Mixed_Other_Trees',
    'Open_Water',
    'Regularly_Flooded_Vegetation',
    'Shrubs',
    'vegetacao_ibge1992_br',
    'solos2001_br',
    'sa2001tree_br',
    'exposicao_br',
    'density3_br',
    'declividade_br',
    'altitude_br',
    'Presence'
]
